apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server
  labels:
    app: go-http-server 
spec:
  selector:
    matchLabels:
      app: go-http-server
  template:
    metadata:
      labels:
        app: go-http-server
    spec:
      containers:
      - name: go-http-server
        image: mustakim/go-http-server
        ports:
        - name: http-port
          containerPort: 9090
